on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v3
      - name: Documntation builder action
        uses: ./ # Uses an action in the root directory
        id: docbuilder
          #with:
          #who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Get the output string
        run: echo "The time was ${{ steps.docbuilder.outputs.outstring }}"
